let g:mapleader = "\<Space>"

const s:denops_src = '~/.cache/dpp/repos/github.com/vim-denops/denops.vim'
const s:denops_hello = '~/.cache/dpp/repos/github.com/vim-denops/denops-helloworld.vim'

execute 'set runtimepath+=' .. s:denops_src
execute 'set runtimepath+=' .. s:denops_hello

const s:dpp_src = '~/.cache/dpp/repos/github.com/Shougo/dpp.vim'
const s:dpp_installer = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-installer'
const s:dpp_local = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-local'
const s:dpp_lazy = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-lazy'
const s:dpp_toml = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-toml'
const s:dpp_git = '~/.cache/dpp/repos/github.com/Shougo/dpp-protocol-git'

execute 'set runtimepath+=' .. s:dpp_src
execute 'set runtimepath+=' .. s:dpp_installer
execute 'set runtimepath+=' .. s:dpp_local
execute 'set runtimepath+=' .. s:dpp_lazy
execute 'set runtimepath+=' .. s:dpp_toml
execute 'set runtimepath+=' .. s:dpp_git

const s:dpp_base = '~/.cache/dpp'
const s:dpp_config = '~/.config/vim/dpp.ts'

if s:dpp_base->dpp#min#load_state()
  autocmd User DenopsReady
        \ : echohl WarningMsg
        \ | echomsg 'dpp load_state() is failed'
        \ | echohl NONE
        \ | call dpp#make_state(s:dpp_base, s:dpp_config)
endif

autocmd User Dpp:makeStatePost
      \ : echohl WarningMsg
      \ | echomsg 'dpp make_state() is done'
      \ | echohl NONE

if has('syntax')
	syntax on
endif

filetype indent plugin on

set nocompatible

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set smartindent
set smarttab

set ignorecase
set smartcase
set hlsearch
set incsearch

set mouse=a
set nobackup
set nowritebackup
set noswapfile
set noundofile

set termguicolors
set background=dark
set nowrap
set cursorline
set signcolumn=yes

nnoremap bd <Cmd>bd<Cr>
nnoremap bn <Cmd>bn<Cr>
nnoremap bp <Cmd>bp<Cr>

" 一時的にvim configに不満があったらすぐにメモできるように一時的に設定
nnoremap <Leader>m <Cmd>e ~/.config/vim/memo.md<Cr>

" Vim側の組み込みプラグインを無効化
let s:save_rtp = &runtimepath
set rtp-=$VIMRUNTIME
autocmd SourcePre */plugin/* ++once let &runtimepath = s:save_rtp
